apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
spec:
  replicas: 2
  selector:
    matchLabels:
      component: products-api
  template:
    metadata:
      labels:
        component: products-api
    spec:
      containers:
        - name: products-api
          image: abdosaudi/ecommerce-node-products-api:v1.2
          ports:
            - containerPort: 5002
          env:
            - name: MONGODB_HOST
              value: "mongodb-cluster-ip-service"
          envFrom:
            - configMapRef:
                name: rabbitmq-configmap
